In [8]:
import numpy as np

from flatland.core.grid.rail_env_grid import RailEnvTransitions
from flatland.core.transition_map import GridTransitionMap
from flatland.envs.grid4_generators_utils import connect_rail_in_grid_map, connect_straight_line_in_grid_map, \
    fix_inner_nodes
from flatland.envs.malfunction_generators import malfunction_from_params, MalfunctionParameters, ParamMalfunctionGen

from flatland.envs.observations import GlobalObsForRailEnv
# First of all we import the Flatland rail environment
from flatland.envs.rail_env import RailEnv
from flatland.envs.rail_env import RailEnvActions
from flatland.envs.rail_generators import sparse_rail_generator
#from flatland.envs.sparse_rail_gen import SparseRailGen
from flatland.envs.line_generators import sparse_line_generator
# We also include a renderer because we want to visualize what is going on in the environment
from flatland.utils.rendertools import RenderTool, AgentRenderVariant

import matplotlib.pyplot as plt




In [9]:
rail_trans = RailEnvTransitions()
grid_map = GridTransitionMap(width=20, height=20, transitions=rail_trans)
grid_map.grid.fill(0)


In [10]:
print(grid_map)

In [11]:
print(grid_map.grid)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [12]:
start_point = (2, 2)
end_point = (8, 8)
connection_001 = connect_rail_in_grid_map(grid_map, start_point, end_point, rail_trans, flip_start_node_trans=True,
                                          flip_end_node_trans=True, respect_transition_validity=True,
                                          forbidden_cells=None)
connection_001_start = (2,2)
connection_001_end = (8, 8)                               
connection_001_expected = (13, connection_001_start,connection_001_end) 
print(connection_001)
# Make connection with open ends on both sides
start_point = (1, 3)
end_point = (1, 7)
connection_002 = connect_rail_in_grid_map(grid_map, start_point, end_point, rail_trans, flip_start_node_trans=False,
                                          flip_end_node_trans=False, respect_transition_validity=True,
                                          forbidden_cells=None)
connection_002_start = (1,3)
connection_002_end = (1, 7)
connection_002_expected = (5, connection_002_start,connection_002_end) 
# Make connection with open end at beginning and dead end on end
start_point = (6, 1)
end_point = (6, 9)
connection_003 = connect_rail_in_grid_map(grid_map, start_point, end_point, rail_trans, flip_start_node_trans=False,
                                          flip_end_node_trans=True, respect_transition_validity=True,
                                        forbidden_cells=None)
connection_003_start = (6,1)
connection_003_end = (6, 9)
connection_003_expected = (9, connection_003_start, connection_003_end)
# Make connection with dead end on start and opend end
start_point = (4, 0)
end_point = (8, 10)
connection_004 = connect_rail_in_grid_map(grid_map, start_point, end_point, rail_trans, flip_start_node_trans=True,
                                          flip_end_node_trans=False, respect_transition_validity=True,
                                          forbidden_cells=None)
connection_004_start = (4,0)
connection_004_end = (8, 10)
connection_004_expected = (15, connection_004_start, connection_004_end)


    




running A*
[(2, 2), (2, 3), (3, 3), (3, 4), (4, 4), (5, 4), (5, 5), (6, 5), (6, 6), (6, 7), (6, 8), (7, 8), (8, 8)]
[(2, 2), (2, 3), (3, 3), (3, 4), (4, 4), (5, 4), (5, 5), (6, 5), (6, 6), (6, 7), (6, 8), (7, 8), (8, 8)]



running A*
[(1, 3), (1, 4), (1, 5), (1, 6), (1, 7)]



running A*
[(6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9)]



running A*
[(4, 0), (4, 1), (4, 2), (5, 2), (5, 3), (6, 3), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (8, 9), (8, 10)]


In [13]:
print(grid_map.grid)

[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [    0     0     0     0  1025  1025  1025     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [    0     0     4  4608     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [    0     0     0    72  4608     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [    4  1025  4608     0 32800     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [    0     0    72  4608    72  4608     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [    0     0  1025 33825  1025  1097  1025  1025  5633   256     0     0
      0     0     0     0     0     0     0     0]
 [    0     0     0    72  1025  1025  1025  1025 33825  4608     0     0
      0     0     0     0     0     0     0     0]


In [15]:
count = 0
for i in range(20):
    row = grid_map.grid[i]
    print(row)
    occupied = row[row>0]
    print(occupied)
    count += len(occupied)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[]
[   0    0    0    0 1025 1025 1025    0    0    0    0    0    0    0
    0    0    0    0    0    0]
[1025 1025 1025]
[   0    0    4 4608    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]
[   4 4608]
[   0    0    0   72 4608    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]
[  72 4608]
[    4  1025  4608     0 32800     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0]
[    4  1025  4608 32800]
[   0    0   72 4608   72 4608    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]
[  72 4608   72 4608]
[    0     0  1025 33825  1025  1097  1025  1025  5633   256     0     0
     0     0     0     0     0     0     0     0]
[ 1025 33825  1025  1097  1025  1025  5633   256]
[    0     0     0    72  1025  1025  1025  1025 33825  4608     0     0
     0     0     0     0     0     0     0     0]
[   72  1025  1025  1025  1025 3382

In [17]:
s1= set(connection_001)
s2 = set(connection_002)
s3= set(connection_003)
s4= set(connection_004)

In [20]:
s = s1.intersection(s2)
s.update(s1.intersection(s3))
s.update(s1.intersection(s4))
s.update(s2.intersection(s3))
s.update(s2.intersection(s4))
s.update(s3.intersection(s4))
print(s)

{(6, 7), (6, 5), (6, 6), (6, 8), (6, 3), (7, 8)}
